### ISSUE TITLE
make @songhay/index styling configurable

### ISSUE THREAD

**Issue by BryanWilhite** [BryanWilhite/songhay-ng-workspace#20]
a conventional and/or configurable external CSS file should provide styling customization for the Index App

continuing on from #11

**Comment by BryanWilhite** [comment]
currently there are only 10 style files in the `@songhay/index` library:
![image](https://user-images.githubusercontent.com/5226627/56309451-73aa2180-60fe-11e9-9cda-709b8aac9ac7.png)

**Comment by BryanWilhite** [comment]
there are two leading ways to parameterize CSS in Angular:

the [2016 way](https://stackoverflow.com/a/35735056/22944), using a plain-old JavaScript object and `[ngStyle]`:
![image](https://user-images.githubusercontent.com/5226627/56311344-a3f3bf00-6102-11e9-9f39-78230acd3b75.png)

[the 2018 way](https://medium.com/@amcdnl/theming-angular-with-css-variables-3c78a5b20b24) with CSS Variables and a full-blown theme directive:
![image](https://user-images.githubusercontent.com/5226627/56311439-dd2c2f00-6102-11e9-9cab-84ee188fd4dc.png)

**Comment by BryanWilhite** [comment]
i have set up a sample study to show myself how to move forward: https://stackblitz.com/edit/ng-style-and-theming

**Comment by BryanWilhite** [comment]
it looks like the dependency on `@angular/flex-layout` can be removed:
![image](https://user-images.githubusercontent.com/5226627/56322129-1376a800-611d-11e9-9e46-9c007508755a.png)

**Comment by BryanWilhite** [comment]
_akyinkyin_ theming has to be removed:
![image](https://user-images.githubusercontent.com/5226627/56325078-be8b5f80-6125-11e9-8bcb-fc5ef3889158.png)

**Comment by BryanWilhite** [comment]
i am totally guessing here:

```scss
a {
    &.index {
        &:link {
            color: var(--link-color);
        }
        &:active {
            color: var(--link-visited-color);
        }
        &:visited {
            color: var(--link-visited-color);
        }

        &:link,
        &:active,
        &:visited {
            text-decoration: var(--link-text-decoration);
        }
        &:hover {
            text-decoration: var(--link-hover-text-decoration);
            text-decoration-color: var(--link-hover-text-decoration-color);
        }
    }
}
```
